name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v15
    - uses: cachix/cachix-action@v10
      with:
        name: znewman01
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix develop --command echo Shell works.
    - run: nix flake check
    - run: nix run .#sssim -- --help
    - run: nix run .#sslogs -- --help
    - run: nix run .#ssanalyze -- --help
    - run: nix build .#e2e-pipeline
